### ISSUE TITLE
项目相关咨询

### ISSUE THREAD

**Issue by day210** [jingjun-xiao/improveRaft#1]
您好，您是打算做共识算法的改进吗，我也在准备做这方面的内容，看到您在[raft-java](https://github.com/wenweihu86/raft-java)里提的issue来的，希望能与您进行进一步的交流学习，具体联系方式通过邮件获取吧，我的邮箱在资料里。

**Comment by jingjun-xiao** [comment]
好呀好呀，我正愁没有人交流呢。可否留下你的微信号之类的，后期可以加好友聊聊

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月24日(周五) 晚上7:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jingjun-xiao/improveRaft] 项目相关咨询 (#1)




 
您好，您是打算做共识算法的改进吗，我也在准备做这方面的内容，看到您在raft-java里提的issue来的，希望能与您进行进一步的交流学习，具体联系方式通过邮件获取吧，我的邮箱在资料里。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DaYu525** [comment]
微信（同qq）20789647



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jingjun-xiao ***@***.***&gt;
发送时间: 2021年9月24日 20:07
收件人: jingjun-xiao/improveRaft ***@***.***&gt;
抄送: Day ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[jingjun-xiao/improveRaft] 项目相关咨询 (#1)





 好呀好呀，我正愁没有人交流呢。可否留下你的微信号之类的，后期可以加好友聊聊 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年9月24日(周五) 晚上7:31 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [jingjun-xiao/improveRaft] 项目相关咨询 (#1) 
 
 
 
 
   
 您好，您是打算做共识算法的改进吗，我也在准备做这方面的内容，看到您在raft-java里提的issue来的，希望能与您进行进一步的交流学习，具体联系方式通过邮件获取吧，我的邮箱在资料里。 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
